# Generated by Django 3.2.9 on 2021-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211125_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='data',
            field=models.CharField(blank=True, max_length=25, verbose_name='sign for css'),
        ),
    ]
