# Generated by Django 3.2.9 on 2021-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='data',
            field=models.CharField(blank=True, default='*', max_length=25, verbose_name='sign for css'),
        ),
    ]
